name: Rust Setup

inputs:
  target:
    description: "Rust Target Architecture"
    required: true

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libseccomp-dev
